// Choosy catalogs registry — AUTO-GENERATED by tools/build-catalogs.js.
// Each catalog is a static JSON file. require() with a static path is bundled
// reliably by Vercel. Re-run the builder to refresh.

module.exports = [
  require('./terminalx-boy-0-2-bodysuits.json'),
  require('./terminalx-boy-0-2-swim.json'),
  require('./terminalx-boy-0-2-tops.json'),
  require('./terminalx-boy-2-8-bottoms.json'),
  require('./terminalx-boy-2-8-swim.json'),
  require('./terminalx-boy-2-8-tops.json'),
  require('./terminalx-girl-0-2-bodysuits.json'),
  require('./terminalx-girl-0-2-dresses.json'),
  require('./terminalx-girl-0-2-swim.json'),
  require('./terminalx-girl-0-2-tops.json'),
  require('./terminalx-girl-2-8-bottoms.json'),
  require('./terminalx-girl-2-8-dresses.json'),
  require('./terminalx-girl-2-8-swim.json'),
  require('./terminalx-girl-2-8-tops.json')
];
